window.LORE = [
  // ---------- SPELLS (12) ----------
  {id:"lumos", name:"Lumos", type:"spell", emoji:"💡", blurb:"A simple charm that makes the tip of your wand glow like a torch. Perfect for dark corridors and night-time wanderings.", fact:"Harry and Ron used Lumos to follow the spiders into the Forbidden Forest in their second year.", danger:1, kw:["light","wand light","glow","lumos","illuminate"]},
  {id:"nox", name:"Nox", type:"spell", emoji:"🌑", blurb:"The counter-charm to Lumos. It puts out the light at the end of your wand.", fact:"Learn Lumos and Nox as a pair: one switches your wand-light on, the other switches it off.", danger:1, kw:["nox","darkness","extinguish","light off","unlight"]},
  {id:"wingardium-leviosa", name:"Wingardium Leviosa", type:"spell", emoji:"🪶", blurb:"The Levitation Charm, which makes objects float into the air. First-years learn it in Professor Flitwick's Charms class.", fact:"Hermione told Ron it's \"Leviosa, not Leviosar\" - and later Ron used the spell to knock out a mountain troll with its own club.", danger:1, kw:["levitate","levitation","float","fly","leviosa","flitwick"]},
  {id:"expelliarmus", name:"Expelliarmus", type:"spell", emoji:"🪄", blurb:"The Disarming Charm knocks your opponent's wand out of their hand. It is one of the most useful defensive spells you can learn.", fact:"Snape demonstrated it at Lockhart's Duelling Club, and it became Harry's signature spell.", danger:2, kw:["disarm","disarming","duel","expelliarmus","defence"]},
  {id:"accio", name:"Accio", type:"spell", emoji:"🧲", blurb:"The Summoning Charm brings an object flying to you. Say \"Accio\" followed by the thing you want.", fact:"Harry summoned his Firebolt with Accio to escape the Hungarian Horntail in the first task of the Triwizard Tournament.", danger:1, kw:["summon","summoning","fetch","accio","call"]},
  {id:"alohomora", name:"Alohomora", type:"spell", emoji:"🔓", blurb:"An unlocking charm that opens locked doors and windows. Handy, but not every lock will give way to it.", fact:"Hermione used Alohomora in first year to open a locked door - which led straight to Fluffy, the three-headed dog.", danger:1, kw:["unlock","open","door","lock","alohomora"]},
  {id:"stupefy", name:"Stupefy", type:"spell", emoji:"💥", blurb:"The Stunning Spell fires a jet of red light that knocks a target unconscious. Dumbledore's Army practised it often.", fact:"Several Stunners at once can bring down even a dragon - dragon keepers use a group of them to subdue one.", danger:3, kw:["stun","stunning","stunner","red light","stupefy"]},
  {id:"protego", name:"Protego", type:"spell", emoji:"🛡️", blurb:"The Shield Charm creates an invisible barrier that blocks or rebounds many jinxes and hexes.", fact:"Harry practised the Shield Charm with Hermione's help while preparing for the third Triwizard task.", danger:1, kw:["shield","block","protect","defence","protego"]},
  {id:"expecto-patronum", name:"Expecto Patronum", type:"spell", emoji:"🦌", blurb:"The Patronus Charm conjures a silvery guardian made of happy memories that drives away Dementors. It is very advanced magic.", fact:"Professor Lupin taught Harry the charm in third year; Harry's Patronus takes the form of a stag, just like his father's Animagus form.", danger:1, kw:["patronus","stag","dementor","guardian","expecto","happy memory"]},
  {id:"riddikulus", name:"Riddikulus", type:"spell", emoji:"🤡", blurb:"The charm used to defeat a Boggart. Picture your fear as something funny, say the incantation, and laughter does the rest.", fact:"In Lupin's class, Neville turned a Boggart-Snape into Snape wearing his grandmother's vulture hat and dress.", danger:1, kw:["boggart","laugh","funny","riddikulus","fear","lupin"]},
  {id:"reparo", name:"Reparo", type:"spell", emoji:"🔧", blurb:"The Mending Charm repairs broken objects, like smashed glass or torn items, in a flash.", fact:"Not everything can be mended: Hermione's Reparo couldn't fix Harry's snapped holly wand - only the Elder Wand could.", danger:1, kw:["repair","fix","mend","mending","reparo"]},
  {id:"incendio", name:"Incendio", type:"spell", emoji:"🔥", blurb:"A fire-making spell that conjures flames from your wand. Useful for lighting fires - and best used with care.", fact:"Mr Weasley used Incendio to light the Dursleys' fireplace so the Floo Network could take Harry to the Quidditch World Cup.", danger:3, kw:["fire","flame","burn","light fire","incendio"]},

  // ---------- CREATURES (10) ----------
  {id:"hippogriff", name:"Hippogriff", type:"creature", emoji:"🦅", blurb:"A proud creature with the front half of a giant eagle and the back half of a horse. Treat it with respect or it may attack.", fact:"Always bow to a Hippogriff and wait for it to bow back before approaching - Hagrid taught this with Buckbeak.", danger:3, kw:["buckbeak","eagle","horse","hagrid","bow","hippogriff"]},
  {id:"thestral", name:"Thestral", type:"creature", emoji:"🐴", blurb:"Skeletal, black winged horses that pull the Hogwarts carriages. Only people who have seen death can see them.", fact:"Thestrals have an excellent sense of direction - Harry and friends rode them to the Ministry of Magic in fifth year.", danger:2, kw:["carriages","winged horse","invisible","death","thestral"]},
  {id:"dementor", name:"Dementor", type:"creature", emoji:"👻", blurb:"Hooded, soul-sucking guards of the wizard prison Azkaban. They drain all happiness from the air around them.", fact:"Eating chocolate helps you recover after a Dementor encounter - Professor Lupin always kept some handy.", danger:5, kw:["azkaban","soul","kiss","cold","patronus","dementor"]},
  {id:"boggart", name:"Boggart", type:"creature", emoji:"🚪", blurb:"A shape-shifter that hides in dark, enclosed spaces and turns into whatever you fear most.", fact:"Harry's Boggart takes the form of a Dementor - Lupin said that meant what Harry feared most was fear itself.", danger:2, kw:["shape-shifter","fear","wardrobe","riddikulus","boggart"]},
  {id:"house-elf", name:"House-elf", type:"creature", emoji:"🧦", blurb:"Small, loyal magical beings who serve wizarding households and work in the Hogwarts kitchens. Their magic is powerful in its own right.", fact:"A house-elf is freed if its master gives it clothes - Harry tricked Lucius Malfoy into freeing Dobby with a sock.", danger:1, kw:["dobby","kreacher","winky","elf","kitchens","sock"]},
  {id:"phoenix", name:"Phoenix", type:"creature", emoji:"🐦‍🔥", blurb:"A brilliant scarlet and gold bird that bursts into flame when old and is reborn from the ashes.", fact:"Phoenix tears have healing powers - Fawkes healed Harry's basilisk wound in the Chamber of Secrets.", danger:1, kw:["fawkes","dumbledore","rebirth","fire bird","tears","phoenix"]},
  {id:"basilisk", name:"Basilisk", type:"creature", emoji:"🐍", blurb:"A gigantic serpent known as the King of Serpents. Looking directly into its eyes is deadly.", fact:"Spiders flee from the Basilisk, and the crowing of a rooster is fatal to it.", danger:5, kw:["serpent","snake","chamber of secrets","slytherin","gaze","basilisk"]},
  {id:"niffler", name:"Niffler", type:"creature", emoji:"🪙", blurb:"A fluffy, black, mole-like creature with a long snout that loves anything shiny. Keep your jewellery close!", fact:"Hagrid had his class use Nifflers to dig up hidden leprechaun gold in fourth year.", danger:1, kw:["shiny","gold","treasure","mole","niffler"]},
  {id:"acromantula", name:"Acromantula", type:"creature", emoji:"🕷️", blurb:"A giant, talking spider with a taste for human flesh. A large colony lives deep in the Forbidden Forest.", fact:"Hagrid raised Aragog, the colony's patriarch, from an egg while he was a student at Hogwarts.", danger:5, kw:["aragog","spider","forbidden forest","giant spider","acromantula"]},
  {id:"hungarian-horntail", name:"Hungarian Horntail", type:"creature", emoji:"🐉", blurb:"A black, lizard-like dragon with bronze horns and a spiked tail. It is considered one of the most dangerous dragon breeds.", fact:"Harry drew the Horntail in the first Triwizard task and had to snatch a golden egg from its nest.", danger:5, kw:["dragon","horntail","triwizard","first task","fire"]},

  // ---------- OBJECTS (8) ----------
  {id:"wand", name:"Wand", type:"object", emoji:"🪄", blurb:"Every witch and wizard's essential tool for channelling magic. Each wand has a wood, a length and a magical core.", fact:"At Ollivanders, \"the wand chooses the wizard\" - Harry's is holly, eleven inches, with a phoenix feather core.", danger:2, kw:["ollivander","ollivanders","core","holly","wand"]},
  {id:"invisibility-cloak", name:"Invisibility Cloak", type:"object", emoji:"🧥", blurb:"A silvery, fluid cloak that makes the wearer completely invisible. Harry's once belonged to his father.", fact:"Harry received it anonymously for Christmas in first year - it later turned out to be one of the three Deathly Hallows.", danger:1, kw:["cloak","invisible","hallows","james potter","sneak"]},
  {id:"marauders-map", name:"Marauder's Map", type:"object", emoji:"🗺️", blurb:"A magical map of Hogwarts that shows where everyone in the castle is at any moment, plus many secret passages.", fact:"Tap it and say \"I solemnly swear that I am up to no good\" to open it, and \"Mischief managed\" to wipe it blank.", danger:1, kw:["map","marauders","moony","wormtail","padfoot","prongs","secret passages"]},
  {id:"sorting-hat", name:"Sorting Hat", type:"object", emoji:"🎩", blurb:"A patched, talking hat that once belonged to Godric Gryffindor. It decides which house each new student joins.", fact:"The Hat sings a new song every year, and a true Gryffindor can pull Gryffindor's sword out of it in a time of need.", danger:1, kw:["hat","sorting","houses","gryffindor","sort"]},
  {id:"time-turner", name:"Time-Turner", type:"object", emoji:"⏳", blurb:"An hourglass on a chain that sends the user back in time - one hour for every turn.", fact:"Hermione used one in third year to attend extra classes, then she and Harry used it to save Sirius and Buckbeak.", danger:4, kw:["time","hourglass","time travel","hermione","turner"]},
  {id:"remembrall", name:"Remembrall", type:"object", emoji:"🔴", blurb:"A glass ball full of smoke that turns red when its owner has forgotten something.", fact:"It tells you that you've forgotten something - but not what! Neville's gran sent him one in first year.", danger:1, kw:["neville","forget","memory","red","remembrall"]},
  {id:"pensieve", name:"Pensieve", type:"object", emoji:"🥣", blurb:"A shallow stone basin used to store and revisit memories. You can dive into a memory and watch it as if you were there.", fact:"Dumbledore kept his Pensieve in a cabinet in his office and used it to show Harry key memories about Voldemort's past.", danger:2, kw:["memories","basin","dumbledore","memory","pensieve"]},
  {id:"howler", name:"Howler", type:"object", emoji:"✉️", blurb:"A red envelope that bursts open and shouts its message at full volume for everyone to hear.", fact:"Open a Howler quickly - if you ignore it, it explodes. Ron got one from his mum after flying the Ford Anglia to school.", danger:2, kw:["letter","red envelope","shout","owl post","mail","howler"]},

  // ---------- TRADITIONS / EVENTS (6) ----------
  {id:"sorting-ceremony", name:"Sorting Ceremony", type:"tradition", emoji:"🏰", blurb:"At the start-of-term feast, first-years are sorted into Gryffindor, Hufflepuff, Ravenclaw or Slytherin by the Sorting Hat.", fact:"First-years arrive by boat across the lake with Hagrid - and the Hat takes your own choice into account.", danger:1, kw:["sorting","houses","first years","great hall","feast","ceremony"]},
  {id:"quidditch", name:"Quidditch", type:"tradition", emoji:"🧹", blurb:"The wizarding world's favourite sport, played on broomsticks by two teams of seven with four balls: a Quaffle, two Bludgers and the Golden Snitch.", fact:"Catching the Golden Snitch earns 150 points and ends the game. Harry became the youngest House Seeker in a century.", danger:3, kw:["broom","snitch","seeker","quaffle","bludger","keeper","chaser","beater","sport"]},
  {id:"house-cup", name:"House Cup", type:"tradition", emoji:"🏆", blurb:"A year-long competition between the four houses. Students earn points for good deeds and lose them for breaking rules.", fact:"In Harry's first year, Dumbledore's last-minute points - including ten to Neville for standing up to his friends - won Gryffindor the Cup.", danger:1, kw:["points","house points","cup","competition","hourglasses"]},
  {id:"yule-ball", name:"Yule Ball", type:"tradition", emoji:"💃", blurb:"A formal Christmas dance held as part of the Triwizard Tournament, open to fourth-years and above (younger students may come if invited).", fact:"The champions and their partners open the dancing, and the wizarding band the Weird Sisters played at the ball.", danger:1, kw:["dance","ball","christmas","dress robes","yule"]},
  {id:"halloween-feast", name:"Halloween Feast", type:"tradition", emoji:"🎃", blurb:"A spooky celebration in the Great Hall on 31 October, with live bats and giant carved pumpkins from Hagrid's patch.", fact:"Halloween is often eventful: in first year, Professor Quirrell burst in shouting that there was a troll in the dungeons.", danger:2, kw:["halloween","pumpkin","feast","bats","troll","october"]},
  {id:"triwizard-tournament", name:"Triwizard Tournament", type:"tradition", emoji:"🏅", blurb:"A dangerous magical contest between Hogwarts, Beauxbatons and Durmstrang. One champion from each school faces three difficult tasks.", fact:"The Goblet of Fire chooses the champions, and Dumbledore drew an Age Line around it so no one under seventeen could enter.", danger:5, kw:["triwizard","goblet of fire","champion","beauxbatons","durmstrang","tournament","tasks"]}
];
